package modelo;
// Generated 6/03/2018 02:07:24 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {
     private int idE;
     private String nombre;
     private String oficinas;
     private Date fundacion;
     private Short numempleados;
     private String contacto;
     private String president;
     private Set vacantes = new HashSet(0);

    public Empresa() {
    }

	
    public Empresa(int idE) {
        this.idE = idE;
    }
    public Empresa(int idE, String nombre, String oficinas, Date fundacion, Short numempleados, String contacto, String president, Set vacantes) {
       this.idE = idE;
       this.nombre = nombre;
       this.oficinas = oficinas;
       this.fundacion = fundacion;
       this.numempleados = numempleados;
       this.contacto = contacto;
       this.president = president;
       this.vacantes = vacantes;
    }
   
    public int getIdE() {
        return this.idE;
    }
    
    public void setIdE(int idE) {
        this.idE = idE;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getOficinas() {
        return this.oficinas;
    }
    
    public void setOficinas(String oficinas) {
        this.oficinas = oficinas;
    }
    public Date getFundacion() {
        return this.fundacion;
    }
    
    public void setFundacion(Date fundacion) {
        this.fundacion = fundacion;
    }
    public Short getNumempleados() {
        return this.numempleados;
    }
    
    public void setNumempleados(Short numempleados) {
        this.numempleados = numempleados;
    }
    public String getContacto() {
        return this.contacto;
    }
    
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }
    public String getPresident() {
        return this.president;
    }
    
    public void setPresident(String president) {
        this.president = president;
    }
    public Set getVacantes() {
        return this.vacantes;
    }
    
    public void setVacantes(Set vacantes) {
        this.vacantes = vacantes;
    }
}


