package modelo;
// Generated 6/03/2018 02:07:24 PM by Hibernate Tools 4.3.1



/**
 * Formacion generated by hbm2java
 */
public class Formacion  implements java.io.Serializable {


     private int idF;
     private Profesionista profesionista;
     private String colegio;
     private String grado;
     private String periodo;

    public Formacion() {
    }

	
    public Formacion(int idF, Profesionista profesionista) {
        this.idF = idF;
        this.profesionista = profesionista;
    }
    public Formacion(int idF, Profesionista profesionista, String colegio, String grado, String periodo) {
       this.idF = idF;
       this.profesionista = profesionista;
       this.colegio = colegio;
       this.grado = grado;
       this.periodo = periodo;
    }
   
    public int getIdF() {
        return this.idF;
    }
    
    public void setIdF(int idF) {
        this.idF = idF;
    }
    public Profesionista getProfesionista() {
        return this.profesionista;
    }
    
    public void setProfesionista(Profesionista profesionista) {
        this.profesionista = profesionista;
    }
    public String getColegio() {
        return this.colegio;
    }
    
    public void setColegio(String colegio) {
        this.colegio = colegio;
    }
    public String getGrado() {
        return this.grado;
    }
    
    public void setGrado(String grado) {
        this.grado = grado;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }




}


