package modelo;
// Generated 6/03/2018 02:07:24 PM by Hibernate Tools 4.3.1



/**
 * Postular generated by hbm2java
 */
public class Postular  implements java.io.Serializable {


     private int idPo;
     private Profesionista profesionista;
     private Vacante vacante;

    public Postular() {
    }

    public Postular(int idPo, Profesionista profesionista, Vacante vacante) {
       this.idPo = idPo;
       this.profesionista = profesionista;
       this.vacante = vacante;
    }
   
    public int getIdPo() {
        return this.idPo;
    }
    
    public void setIdPo(int idPo) {
        this.idPo = idPo;
    }
    public Profesionista getProfesionista() {
        return this.profesionista;
    }
    
    public void setProfesionista(Profesionista profesionista) {
        this.profesionista = profesionista;
    }
    public Vacante getVacante() {
        return this.vacante;
    }
    
    public void setVacante(Vacante vacante) {
        this.vacante = vacante;
    }




}


