package modelo;
// Generated 6/03/2018 02:07:24 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Profesionista generated by hbm2java
 */
public class Profesionista  implements java.io.Serializable {


     private int idPro;
     private String nombre;
     private String correo;
     private String telefono;
     private String contrasena;
     private String nacionalidad;
     private String carrera;
     private Set habilidadeses = new HashSet(0);
     private Set explaborals = new HashSet(0);
     private Set formacions = new HashSet(0);
     private Set postulars = new HashSet(0);

    public Profesionista() {
    }

	
    public Profesionista(int idPro) {
        this.idPro = idPro;
    }
    public Profesionista(int idPro, String nombre, String correo, String telefono, String contrasena, String nacionalidad, String carrera, Set habilidadeses, Set explaborals, Set formacions, Set postulars) {
       this.idPro = idPro;
       this.nombre = nombre;
       this.correo = correo;
       this.telefono = telefono;
       this.contrasena = contrasena;
       this.nacionalidad = nacionalidad;
       this.carrera = carrera;
       this.habilidadeses = habilidadeses;
       this.explaborals = explaborals;
       this.formacions = formacions;
       this.postulars = postulars;
    }
   
    public int getIdPro() {
        return this.idPro;
    }
    
    public void setIdPro(int idPro) {
        this.idPro = idPro;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public String getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(String carrera) {
        this.carrera = carrera;
    }
    public Set getHabilidadeses() {
        return this.habilidadeses;
    }
    
    public void setHabilidadeses(Set habilidadeses) {
        this.habilidadeses = habilidadeses;
    }
    public Set getExplaborals() {
        return this.explaborals;
    }
    
    public void setExplaborals(Set explaborals) {
        this.explaborals = explaborals;
    }
    public Set getFormacions() {
        return this.formacions;
    }
    
    public void setFormacions(Set formacions) {
        this.formacions = formacions;
    }
    public Set getPostulars() {
        return this.postulars;
    }
    
    public void setPostulars(Set postulars) {
        this.postulars = postulars;
    }




}


